language: python
python:
  - 3.6

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - export PATH=$PATH:~/.poetry/bin
  - poetry install

script:
  - poetry run mkdocs build

deploy:
  provider: pages
  local-dir: site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
