site_name: Техническая документация для инженеров
site_author: Константин Молчанов

repo_name: moigagoo/techdocs
repo_url: https://github.com/moigagoo/techdocs
edit_uri: edit/develop/docs/

nav:
  - День 1:
    - day1/words.md
    - day1/sentences.md
    - day1/document.md
  - День 2:
    - day2/kinds.md
    - day2/tools.md
    - day2/rdd.md

theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  language: ru

markdown_extensions:
  - admonition
